// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFEh1qpKT7rdhdaflEDDjISlX8T0g5Lqg',
    appId: '1:553611032865:web:ee841ec5bcbce1b1d12660',
    messagingSenderId: '553611032865',
    projectId: 'galonfirebase',
    authDomain: 'galonfirebase.firebaseapp.com',
    storageBucket: 'galonfirebase.firebasestorage.app',
    measurementId: 'G-2YPXK8V7R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbUvPIH-yTGHA5t62KEqwfMyAI0s48vxE',
    appId: '1:553611032865:android:4d6d50da15a067dbd12660',
    messagingSenderId: '553611032865',
    projectId: 'galonfirebase',
    storageBucket: 'galonfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcJ3Q3d1HVcLkEZlgGhUiWdGFTYG8jYk',
    appId: '1:553611032865:ios:0c2f099ba4fd57a4d12660',
    messagingSenderId: '553611032865',
    projectId: 'galonfirebase',
    storageBucket: 'galonfirebase.firebasestorage.app',
    iosBundleId: 'com.example.galonfibonacci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGcJ3Q3d1HVcLkEZlgGhUiWdGFTYG8jYk',
    appId: '1:553611032865:ios:0c2f099ba4fd57a4d12660',
    messagingSenderId: '553611032865',
    projectId: 'galonfirebase',
    storageBucket: 'galonfirebase.firebasestorage.app',
    iosBundleId: 'com.example.galonfibonacci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFEh1qpKT7rdhdaflEDDjISlX8T0g5Lqg',
    appId: '1:553611032865:web:bfb4f8897c8eb2aed12660',
    messagingSenderId: '553611032865',
    projectId: 'galonfirebase',
    authDomain: 'galonfirebase.firebaseapp.com',
    storageBucket: 'galonfirebase.firebasestorage.app',
    measurementId: 'G-WET97PKN3L',
  );
}
